name: "CD pipeline"
on:
  workflow_run:
     workflows: [ "CI pipeline" ]
     types:
        - completed

jobs:
  cd-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        run: echo "CI pipeline succeeded"

