name: "CI pipeline"
on:
  push:
    branches:
      - master
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: print the kernel version
        run: uname -r

      - name: print the os version
        run: cat /etc/os-release


