name: "Sample react react pipeline"
on:
  push:
    branches:
      - main
      - master
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: '21'


      - name: check the node version
        run: node --version
